name = "cycutaipei"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
APP_URL = "https://cycutaipei.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "cycutaipei-db"
database_id = "467ef5cc-0f85-4cb4-88e6-acc54f5c6484"
migrations_dir = "../migrations"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cycutaipei-media"
